name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  desktop:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install tauri-bundler --force

      - if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - run: npm i

      - id: get_version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: quantu-${{ steps.branch_name.outputs.SOURCE_TAG }}
          releaseName: quantu-${{ steps.branch_name.outputs.SOURCE_TAG }}
